name: Super-Linter

on: push

jobs:
  super-lint:
    name: Linkt code base
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}	
